# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kerick Howlett | Web Developer
email: kahowlett1989@gmail.com
description: Hey, I'm Kerick Howlett and Louisville's tallest Application Developer, Full-Stack Developer, and Software Engineer with a
    knack for creative solutions in programming. I specialize in PHP, JavaScript, TypeScript
    Angular, jQuery, and Hybrid WebView Mobile App development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thetallestdeveloper.com/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  bigk5000
linkedin_username: kerickhowlett
twitter_username: TheTallestDev

# Build settings
markdown: kramdown
theme: minima
gems:
    - jekyll-feed
    - jekyll-sitemap
exclude:
    - Gemfile
    - Gemfile.lock

# New permalink structure for posts
permalink: /blog/:title/

# New document type
# Source: https://jekyllrb.com/docs/collections/
# More on collections here: http://ben.balter.com/2015/02/20/jekyll-collections/
collections:
    projects:
        output: true
        permalink: /projects/:title/

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - examples
